### ISSUE TITLE
Operators with "then" should be "than"

### ISSUE THREAD

**Issue by ssiltanen** [tforkmann/AzureTackle#2]
Sorry for making misspelling issue but thought it would be better to notice it earlier than later.

    | LessThen
    | LessThenOrEqual
    | GreaterThen
    | GreaterThenOrEqual

**Comment by tforkmann** [comment]
Ups yes thank you :) will fix that

**Comment by tforkmann** [comment]
Was only wrong in the Readme file. Fix now
